# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.output_dir}/tensorboard/"
  name: cifar10_hyperparam_search
  log_graph: False
  default_hp_metric: False
  prefix: ""
  # version: ""
